In [30]:
import numpy as np

In [31]:
from sklearn.datasets import load_iris

iris = load_iris()

In [32]:
type(iris)

sklearn.utils.Bunch

In [ ]:
#print(iris.DESCR)

In [34]:
X = iris.data
#X

In [35]:
y = iris.target
#y

### Pre-Processing

#### One Hot Encoding <br>
class 0 --> [1,0,0] <br>
class 1 --> [0,1,0] <br>
class 2 --> [0,0,1] <br>

In [36]:
from keras.utils import to_categorical

In [37]:
y = to_categorical(y)

In [38]:
y.shape

(150, 3)

In [39]:
# y

#### Splitting Data

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.33, random_state = 42)

In [ ]:
#X_train

#### Standardize

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
# EXAMPLE
np.array([5,10,15,20]) / 20

array([0.25, 0.5 , 0.75, 1.  ])

In [45]:
scaler_object = MinMaxScaler()

In [46]:
scaler_object.fit(X_train)

MinMaxScaler()

In [47]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [ ]:
# All Values are now between 0 and 1
#scaled_X_train

### Building the Network

In [50]:
from keras.models import Sequential
from keras.layers import Dense

In [51]:
model = Sequential()

# First Layer -> 8 (8 Neurons), input_dim = 4 (Expecting 4 Features), (ReLU as Activation Function)
model.add(Dense(8, input_dim = 4, activation = 'relu'))

# Second Layer 
model.add(Dense(8, input_dim = 4, activation = 'relu'))

# Output Layer -> 3 (Expected 3 Output), (Softmax as Activation Function (see Notebook))
model.add(Dense(3, activation = 'softmax'))     # [0.2, 0.3, 0.5]


model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [52]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [53]:
model.fit(scaled_X_train, y_train, epochs = 150, verbose = 2)

# epocs -> running through the entire training data set
# verbose -> how much information output do you want while running the network

Epoch 1/150
4/4 - 1s - loss: 1.2134 - accuracy: 0.3500 - 584ms/epoch - 146ms/step
Epoch 2/150
4/4 - 0s - loss: 1.2008 - accuracy: 0.3500 - 5ms/epoch - 1ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1901 - accuracy: 0.3500 - 7ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1784 - accuracy: 0.3700 - 7ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1681 - accuracy: 0.3800 - 6ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1570 - accuracy: 0.3900 - 6ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1463 - accuracy: 0.4100 - 6ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1382 - accuracy: 0.4300 - 6ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1291 - accuracy: 0.4900 - 6ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1220 - accuracy: 0.5200 - 7ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1164 - accuracy: 0.5300 - 6ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.1102 - accuracy: 0.5400 - 7ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.1049 - accuracy: 0.5300 -

### Predicting our Test Data

In [ ]:
model.predict(scaled_X_test)

# Shows Probability of Belonging to Each Class

In [65]:
# Original Code from Course - Error
# model.predict_classes(scaled_X_test)

# np.argmax(,axis=1)

np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 2ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [66]:
# Original Code from Course - Error
# predictions = model.predict_classes(scaled_X_test)

predictions = np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 2ms/step


In [63]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [68]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [69]:
confusion_matrix(y_test.argmax(axis = 1), predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]], dtype=int64)

In [70]:
print(classification_report(y_test.argmax(axis = 1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [71]:
accuracy_score(y_test.argmax(axis = 1), predictions)

0.96

### Saving Our Model !
If running a super large model, especially for things like text generation that can take hours to run, we wanna be able to save and load our model.

In [72]:
model.save('myfirstmodel.h5')

# Be Carefull about Overwriting your model with the same model name !

In [73]:
from keras.models import load_model

In [74]:
new_model = load_model('myfirstmodel.h5')

In [75]:
np.argmax(new_model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 2ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)